[profile.default]
src = 'src'
out = 'out'

optimizer = true
optimizer_runs = 10_000

[fmt]
line_length = 120
tab_width = 2
bracket_spacing = false
int_types = 'short'
func_attrs_with_params_multiline = false
quote_style = 'double'

# See more config options https://github.com/foundry-rs/foundry/tree/master/config